# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alvinjhson
# "service" is the name of this project. This will also be added to your AWS resource names.
service: AgrimachineryAPI

provider:
  name: aws
  runtime: nodejs20.x
  profile: test
  region: eu-north-1
  iam:
    role: arn:aws:iam::225989356862:role/lectures-cloud 

package:
  individually: true  

build:
  esbuild:
    minify: true  


functions:
  signUp:
    handler: functions/signup/index.handler
    events:
      - httpApi:
          path: /user/signup
          method: POST